# fly.toml app configuration file generated for tetris-scoreboard on 2026-06-14T12:08:54Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tetris-scoreboard'
primary_region = 'cdg'

[build]

[env]
  ALLOWED_ORIGINS = '*'
  DB_PATH = '/data/scores.db'
  PORT = '8080'

[[mounts]]
  source = 'tetris_data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
